---
# Reference: https://github.com/clickfreak/kong-ansible-docker/blob/master/site.yml

- name: Start Postgresql container
  docker_container:
    name: kong-database
    image: postgres:9.5
    state: started
    volumes:
      - /pgdata:/var/lib/postgresql/kong_database
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_DB: kong
  register: postgres_container

- name: Start kong container
  docker_container:
    name: kong
    image: "kong:0.11.0"
    state: started
    links:
      - kong-database:kong-database
    published_ports:
      - 8000:8000
      - 8001:8001
    command: bash -c "kong migrations up && kong start"
    env:
      KONG_PG_PASSWORD: "{{ postgres_password }}"
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: kong-database
      KONG_PG_USER: "{{ postgres_user }}"
  register: kong_container

- name: Remove kong upstreams
  uri:
    url: "http://localhost:8001/upstreams/{{ item.name }}"
    method: DELETE
    status_code: 204
  with_items:
    - { name: 'collector.v1.service' }
    - { name: 'adaptor.v1.service' }
    - { name: 'discovery.v1.service' }
    - { name: 'actuator.v1.service' }
    - { name: 'catalog.v1.service' }
  ignore_errors: yes

